# Generated by Django 5.0.4 on 2024-04-22 12:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to=core.models.user_avatar_upload_path),
        ),
    ]
