# Generated by Django 5.0.4 on 2024-04-26 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created',
            new_name='timestamp',
        ),
    ]
