# Generated by Django 5.0.4 on 2024-04-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_created_message_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmedia',
            old_name='created',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='chatmedia',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='media',
            field=models.ManyToManyField(blank=True, to='core.chatmedia'),
        ),
    ]
